import nextVitals from 'eslint-config-next/core-web-vitals'
import nextTs from 'eslint-config-next/typescript'
import prettier from 'eslint-config-prettier/flat'
import { defineConfig, globalIgnores } from 'eslint/config'

// No stock rule asserts that an import is *present*, so this one is local.
// Kept in the flat config rather than as a script in `pnpm run ci` so it also
// reports in the editor, where the missing import is still cheap to add.
const localPlugin = {
  rules: {
    'require-server-only': {
      meta: {
        type: 'problem',
        docs: { description: "Require `import 'server-only'` in a module." },
        schema: [],
        messages: {
          missing:
            "This module must `import 'server-only'`. Without it, nothing stops it being pulled into a client bundle — a Prisma client for src/lib/db, a Plaid access token for src/lib/plaid.",
        },
      },
      create(context) {
        let found = false
        return {
          ImportDeclaration(node) {
            // Position is irrelevant: the guard works by the bundler seeing
            // the dependency in the module graph, not by evaluation order.
            if (
              node.source.value === 'server-only' &&
              node.importKind !== 'type'
            )
              found = true
          },
          'Program:exit'(node) {
            if (!found) context.report({ node, messageId: 'missing' })
          },
        }
      },
    },
  },
}

const eslintConfig = defineConfig([
  ...nextVitals,
  ...nextTs,
  prettier,
  // Override default ignores of eslint-config-next.
  globalIgnores([
    // Default ignores of eslint-config-next:
    '.next/**',
    'out/**',
    'build/**',
    'next-env.d.ts',
    // Generated by `prisma generate`; not ours to lint.
    'src/generated/**',
  ]),
  {
    // Only the app and the action layer may reach the data layer at runtime.
    //
    // `src/lib/db/*` and `src/lib/plaid/*` take the caller's identity as an
    // argument and do no session check of their own, so an import from a third
    // place is how a query escapes its `requireUser()` guard — and, for
    // `plaid/`, how an access token reaches a module that has no business
    // holding one. The layer is allowed to import itself (`db/errors`,
    // `plaid/client`), and `test/**` is out of scope by design: the integration
    // suite calls these directly, which is the point of the `userId` parameter.
    //
    // Type-only imports are allowed. AGENTS.md prescribes them — types live in
    // the db module — and `import type` is erased, so it adds nothing to the
    // module graph. That allowance is why this is the `@typescript-eslint`
    // rule: the base rule has no `allowTypeImports`.
    files: ['src/**/*.{ts,tsx}'],
    ignores: [
      'src/app/**',
      'src/lib/actions/**',
      'src/lib/db/**',
      'src/lib/plaid/**',
    ],
    rules: {
      '@typescript-eslint/no-restricted-imports': [
        'error',
        {
          patterns: [
            {
              group: ['@/lib/db/**', '@/lib/plaid/**'],
              allowTypeImports: true,
              message:
                'Only src/app/** and src/lib/actions/** may import the data layer at runtime; go through a server action. Type-only imports (import type) are fine.',
            },
          ],
        },
      ],
    },
  },
  {
    // `'use server'` publishes every export as a POST-reachable action id, so
    // the directive belongs only where the entry-point contract is enforced:
    // `requireUser()` per export, `actionError` on the way out.
    //
    // Unlike the private app there is no pre-authentication exception here.
    // Sessions are created by the Better Auth anonymous plugin on the way in,
    // not by a user-facing sign-in action, so every `'use server'` export in
    // this app genuinely does have a user by the time it runs.
    files: ['src/**/*.{ts,tsx}'],
    ignores: ['src/lib/actions/**/*.ts'],
    rules: {
      'no-restricted-syntax': [
        'error',
        {
          selector: "ExpressionStatement > Literal[value='use server']",
          message:
            "'use server' belongs in src/lib/actions/**, where requireUser() and actionError are applied to every export.",
        },
      ],
    },
  },
  {
    // The data layer's own guard. See `localPlugin` above for why it is local
    // and why presence — not position — is what is checked.
    files: ['src/lib/db/**/*.ts', 'src/lib/plaid/**/*.ts'],
    plugins: { local: localPlugin },
    rules: {
      'local/require-server-only': 'error',
    },
  },
  {
    rules: {
      '@typescript-eslint/no-unused-vars': [
        'warn',
        {
          // Destructuring a property solely to omit it from `...rest` is an
          // intentional pattern, not an unused variable.
          ignoreRestSiblings: true,
          argsIgnorePattern: '^_',
          varsIgnorePattern: '^_',
          caughtErrorsIgnorePattern: '^_',
        },
      ],
    },
  },
])

export default eslintConfig
